/*
Student name: Xavier El Chantiry
Student ID: A01229374 
date: 2022-12-07
Pipeline description: Pipeline for the 4850 final that build, tests, and packages a simple python application.
*/
pipeline {
    agent any
    parameters {
        booleanParam(defaultValue: false, description: 'Run Unit Tests', name: 'TEST')
    }
    stages {
        stage('Build') {
            steps {
                script {
                    sh 'echo "Student Name: Xavier El Chantiry \n Student ID: A01229374 \n Group: 23 "'

                    sh 'echo "Installing the Python Requirements..."'
                    sh "pip install -r requirements.txt"
                    sh 'echo "Requirement complete."'
                } 
            }
        }
        stage('Code Quality') {
                steps {
                    sh 'pylint-fail-under --fail_under 7.0 *.py'
                }
            }
        stage("Code Quantity") {
            steps {
                sh 'echo $(ls *.py  | wc -l)'
            }
        }
        stage('Test') {
            when {
                expression { params.TEST }
            }
            steps {
                script{
                    def rmfiles = findFiles(glob: "*reports/*.xml")
                    for (rmfile in rmfiles) {
                        sh "rm ${rmfile.path}"
                    }
                    def files = findFiles(glob: "test*.py")
                    for (file in files){
                        sh "coverage run --omit */site-packages/*,*/dist-packages/* ${file.path}"
                    }
                    sh "coverage report"
                }
            }
            post {
                always {
                    junit "*reports/*.xml"
                }
            }
        }
        stage('Zip Artifacts'){
            steps{
                sh "zip package.zip *.py"
                archiveArtifacts artifacts: 'package.zip', 
                    fingerprint: true, 
                    onlyIfSuccessful: true
            }
        }
    }
}
